# Generated by Django 5.2.1 on 2025-05-18 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('WATER_LEVEL', 'Water Level Sensor'), ('FLOW_METER', 'Flow Meter'), ('QUALITY', 'Quality Sensor')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('last_reading', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(choices=[('5_GALLON', '5 Gallon'), ('10_GALLON', '10 Gallon'), ('20_GALLON', '20 Gallon')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('operating_hours_start', models.TimeField()),
                ('operating_hours_end', models.TimeField()),
                ('pricing_five_gallon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_ten_gallon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_twenty_gallon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notifications_low_water_level', models.BooleanField(default=True)),
                ('notifications_order_updates', models.BooleanField(default=True)),
                ('notifications_device_alerts', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Station Settings',
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('quality_metrics', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='backend.device')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_settings', models.JSONField(default=dict)),
                ('system_preferences', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
