# Generated by Django 5.2 on 2025-06-02 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TankRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refill_date', models.DateTimeField(auto_now_add=True)),
                ('initial_level', models.FloatField(help_text='Water level before refill')),
                ('final_level', models.FloatField(help_text='Water level after refill')),
                ('amount_added', models.FloatField(help_text='Amount of water added in liters')),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(limit_choices_to={'device_type': 'WATER_LEVEL'}, on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
            options={
                'verbose_name': 'Tank Refill Log',
                'verbose_name_plural': 'Tank Refill Logs',
                'ordering': ['-refill_date'],
            },
        ),
    ]
